// <auto-generated />
namespace MeetUp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class message_update_adm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message_update_adm));
        
        string IMigrationMetadata.Id
        {
            get { return "201901100813291_message_update_adm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
